### ISSUE TITLE
Dynamic libraries not enabled; check your Lua installation

### ISSUE THREAD

**Issue by 5up3rD4n1** [TitanSnow/ffilupa#1]
Hi I.m trying to rewrite this: [chdkptp.py](https://github.com/jbaiter/chdkptp.py) and when I try to load the library `chdkptp.so` to lua, I get this error:

```
File "/home/dsolis/.virtualenvs/librescan/lib/python3.6/site-packages/ffilupa/py_from_lua.py", line 531, in __call__
    raise LuaErr.newerr(status, err_msg, self._runtime.encoding)
ffilupa.exception.LuaErrRun: error loading module 'chdkptp' from file './chdkptp.so':
	dynamic libraries not enabled; check your Lua installation
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	python:2: in main chunk
```

I read the documentation but didn't see any Lua installation options.

**Comment by TitanSnow** [comment]
Which version of ffilupa you are using? These days I'm developing the coming version of ffilupa — 2.3.0. The lastest version I released on PyPI is 2.1 series.

In the old versions, the lua library was tied to ffilupa. You can see https://github.com/TitanSnow/ffilupa/tree/81bd3e, I put complete lua source in ffilupa's repo and compile it during installation. By this way, the lua library used by ffilupa had nothing to do with the lua library installed in system, and could not use lua module installed in system-wide lua distribution.

The comming 2.3, however, uses the system-wide lua libraries, in this way ffilupa does not compile a own lua library, instead, it dynamic links to the lua library installed in system. For example, if you use ubuntu or so, and you have installed [liblua5.3-dev](https://packages.ubuntu.com/artful/liblua5.3-dev), then ffilupa uses it so that all modules installed to lua5.3 in system-wide can be used in ffilupa.

I assume that you know [luarocks](https://luarocks.org/) and set up lua distribution with development files (`-dev` shuffix for lua package) and luarocks in your system. Then you can install the newest ffilupa from master tree:

```console
$ pip install git+https://github.com/TitanSnow/ffilupa.git    # or pip3, as the new version needs python3
```

During the installation, it will find lua distribution automatically.

You can install lua module using luarocks or in other ways you like:

```console
$ luarocks install chdkptp    # I'm not sure if it's the name of that package
```

Then you can use it in ffilupa. If you have multiple lua libraries, you can have a look through [ffilupa.lualibs](https://github.com/TitanSnow/ffilupa/blob/ffi/ffilupa/lualibs.py) to learn how to specify a lua library to use.

Sorry but the documentation of new version is just being written. The new version is under development but almost finished. You can have a try.

At last, thanks for using ffilupa! Without users, it cannot become better.

**Comment by 5up3rD4n1** [comment]
Hi @TitanSnow Thank you for your response, I will love to try ffilupa, sadly chdkptp is not a luarocks package, maybe you can take a look and see if it is possible to upload a version of [chdkptp](https://github.com/svn2github/chdkptp) to `luarocks`. That will be great and easy to use the library with `ffilupa`. You helped me out with the `latin-1` encode thing at the `lupa` repo. But I will love to try `ffilupa`, whenever the new version is ready, please tag me here I will like to use this instead of `lupa` this seems to have a better control of encoding and errors. Again thanks for the fast response!

**Comment by TitanSnow** [comment]
Well, if it's a `*.so` file, you can just put it into the current directory and `require` it.

**Comment by R-ay** [comment]
Hey @5up3rD4n1, maybe it's to late now, but I used ffilupa for chdkptp, and it worked great.

I use ffilupa 3.0.1, and python 3.7.5.

Basically, you have to do :
   ```
CHDKPTP_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            'vendor', 'chdkptp')
logger = logging.getLogger('chdkptp.lua')

[...]

 def __init__(self):
        ffilupa.set_default_lualib(ffilupa.get_lualibs().select_name('lua52'))
        self._rt = ffilupa.LuaRuntime()
        self._setup_runtime()

    def _setup_runtime(self):
        # Set up module paths
        self._rt.execute("""
            CHDKPTP_PATH = '{0}'
            package.path = CHDKPTP_PATH .. '/lua/?.lua;' .. package.path
            package.cpath = CHDKPTP_PATH .. '/?.so;' .. package.path
        """.format(CHDKPTP_PATH))

        # Load chdkptp modules
        self._rt.execute("""
               require('chdkptp')
               util = require('util')
               util:import()
               varsubst = require('varsubst')
               chdku = require('chdku')
               exposure = require('exposure')
               dng = require('dng')
               prefs = require('prefs')
               fsutil = require('fsutil')
               ustime = require('ustime')
               errutil = require('errutil')
               cli = require('cli')
           """.format(CHDKPTP_PATH))

        # Enable debug logging
        self._rt.execute("""
            prefs._set('cli_verbose', 2)
        """)

        # Register loggers
        self._rt.eval("""
            function(logger)
                cli = {}
                cli.infomsg = function(...)
                    logger.info(string.format(...):match( "(.-)%s*$" ))
                end
                cli.dbgmsg = function(...)
                    logger.debug(string.format(...):match('(.-)%s*$'))
                end
            end
        """)(logger)
        # Create global connection object
        self._rt.execute("""
            con = chdku.connection()
        """)
```
